/*
 * This source file was generated by the Gradle 'init' task
 */
package us.tlapl;

import tla2sany.parser.TLAplusParser;

public class Checker {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Checker().getGreeting());
    }
}
